<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DemoProductSeeder extends Seeder
{
    public function run(): void
    {
        // Brands
        $brands = [];
        foreach (['Daikin' => 'daikin', 'LG' => 'lg', 'Panasonic' => 'panasonic', 'Gree' => 'gree', 'Mitsubishi' => 'mitsubishi'] as $name => $slug) {
            $brands[$slug] = Brand::firstOrCreate(['slug' => $slug], ['name' => $name, 'is_active' => true]);
        }

        // Categories
        $main = ProductCategory::firstOrCreate(['slug' => 'dieu-hoa-tu-dung'], ['name' => 'Dieu hoa tu dung']);
        $cats = [];
        foreach (['Inverter' => 'inverter', 'Non-Inverter' => 'non-inverter', '1 Chieu' => '1-chieu', '2 Chieu' => '2-chieu'] as $n => $s) {
            $cats[$s] = ProductCategory::firstOrCreate(['slug' => "dieu-hoa-tu-dung-$s"], ['name' => $n, 'parent_id' => $main->id]);
        }

        $products = [
            [
                'name' => 'Dieu hoa tu dung Daikin FVFC71AV1 24000BTU Inverter',
                'sku' => 'DAIKIN-FVFC71AV1',
                'model_code' => 'FVFC71AV1/RZFC71DVM',
                'brand' => 'daikin', 'btu' => 24000, 'inverter' => true,
                'cooling_type' => '1 chieu', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R32', 'power_consumption' => '2.34 kW',
                'airflow' => '1100 m3/h', 'noise_level' => '38/48 dB',
                'indoor_dimensions' => '1680 x 290 x 790 mm',
                'outdoor_dimensions' => '940 x 340 x 990 mm',
                'weight' => '37/62 kg', 'recommended_area' => '25-35 m2',
                'regular_price' => 28500000, 'sale_price' => 25900000,
                'is_featured' => true, 'is_bestseller' => true, 'is_new' => true,
                'short_description' => 'Dieu hoa tu dung Daikin Inverter 24000BTU, tiet kiem dien, gas R32 than thien moi truong.',
                'long_description' => '<h2>Dieu hoa tu dung Daikin FVFC71AV1 Inverter 24000BTU</h2><p>San pham dieu hoa tu dung cao cap cua Daikin voi cong nghe Inverter tiet kiem den 40% dien nang. Thiet ke sang trong, phu hop voi phong khach, van phong, cua hang.</p><h3>Tinh nang noi bat</h3><ul><li>Cong nghe Inverter tiet kiem dien</li><li>Gas R32 than thien moi truong</li><li>Che do gio 3D thoai mai</li><li>Van hanh em ai chi 38dB</li></ul>',
                'warranty_info' => 'Bao hanh may nen 5 nam, lien may 2 nam',
                'installation_note' => 'Mien phi lap dat tieu chuan trong noi thanh. Ong dong max 15m.',
                'specs_json' => [
                    ['label' => 'Cong suat lanh', 'value' => '24.000 BTU/h (7.1 kW)'],
                    ['label' => 'Cong nghe', 'value' => 'Inverter'],
                    ['label' => 'Gas lanh', 'value' => 'R32'],
                    ['label' => 'Nguon dien', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Cong suat tieu thu', 'value' => '2.34 kW'],
                    ['label' => 'Luu luong gio', 'value' => '1100 m3/h'],
                    ['label' => 'Do on dan lanh', 'value' => '38 dB'],
                    ['label' => 'Do on dan nong', 'value' => '48 dB'],
                    ['label' => 'Kich thuoc dan lanh', 'value' => '1680 x 290 x 790 mm'],
                    ['label' => 'Kich thuoc dan nong', 'value' => '940 x 340 x 990 mm'],
                    ['label' => 'Trong luong dan lanh', 'value' => '37 kg'],
                    ['label' => 'Trong luong dan nong', 'value' => '62 kg'],
                    ['label' => 'Dien tich phong', 'value' => '25 - 35 m2'],
                    ['label' => 'Xuat xu', 'value' => 'Thai Lan'],
                ],
                'seo_title' => 'Dieu Hoa Tu Dung Daikin FVFC71AV1 24000BTU Inverter | Gia Tot',
                'seo_description' => 'Mua dieu hoa tu dung Daikin 24000BTU Inverter chinh hang. Gas R32, tiet kiem 40% dien. Bao hanh 5 nam. Giao hang mien phi.',
            ],
            [
                'name' => 'Dieu hoa tu dung Daikin FVGR10PV1 36000BTU Non-Inverter',
                'sku' => 'DAIKIN-FVGR10PV1',
                'model_code' => 'FVGR10PV1/RUR10NY1',
                'brand' => 'daikin', 'btu' => 36000, 'inverter' => false,
                'cooling_type' => '1 chieu', 'voltage' => '3 pha 380V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '3.65 kW',
                'airflow' => '1500 m3/h', 'noise_level' => '42/52 dB',
                'indoor_dimensions' => '1830 x 360 x 850 mm',
                'outdoor_dimensions' => '1100 x 380 x 1170 mm',
                'weight' => '52/85 kg', 'recommended_area' => '35-50 m2',
                'regular_price' => 38500000, 'sale_price' => 35900000,
                'is_featured' => true,
                'short_description' => 'Dieu hoa tu dung Daikin 36000BTU 3 pha cong suat lon, phu hop nha xuong, showroom.',
                'long_description' => '<h2>Dieu hoa tu dung Daikin FVGR10PV1 36000BTU</h2><p>Dong dieu hoa tu dung cong suat lon 36000BTU, su dung nguon 3 pha 380V, phu hop cho nha xuong, showroom, phong hop lon.</p>',
                'warranty_info' => 'Bao hanh may nen 5 nam, lien may 2 nam',
                'installation_note' => 'Yeu cau nguon dien 3 pha. Ong dong max 20m.',
                'specs_json' => [
                    ['label' => 'Cong suat lanh', 'value' => '36.000 BTU/h (10.5 kW)'],
                    ['label' => 'Cong nghe', 'value' => 'Non-Inverter'],
                    ['label' => 'Gas lanh', 'value' => 'R410A'],
                    ['label' => 'Nguon dien', 'value' => '3 pha, 380V/50Hz'],
                    ['label' => 'Dien tich phong', 'value' => '35 - 50 m2'],
                    ['label' => 'Xuat xu', 'value' => 'Thai Lan'],
                ],
                'seo_title' => 'Dieu Hoa Tu Dung Daikin 36000BTU 3 Pha | Cong Suat Lon',
                'seo_description' => 'Dieu hoa tu dung Daikin 36000BTU 3 pha, phu hop nha xuong, showroom. Chinh hang, bao hanh 5 nam.',
            ],
            [
                'name' => 'Dieu hoa tu dung LG APNQ48GT3E4 48000BTU Inverter',
                'sku' => 'LG-APNQ48GT3E4',
                'model_code' => 'APNQ48GT3E4',
                'brand' => 'lg', 'btu' => 48000, 'inverter' => true,
                'cooling_type' => '1 chieu', 'voltage' => '3 pha 380V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '4.2 kW',
                'airflow' => '2200 m3/h', 'noise_level' => '40/54 dB',
                'indoor_dimensions' => '1850 x 350 x 640 mm',
                'outdoor_dimensions' => '1340 x 380 x 1350 mm',
                'weight' => '55/95 kg', 'recommended_area' => '50-70 m2',
                'regular_price' => 52000000, 'sale_price' => 47500000,
                'is_featured' => true, 'is_new' => true,
                'short_description' => 'Dieu hoa tu dung LG Inverter 48000BTU cong suat lon, thiet ke hien dai, tiet kiem nang luong.',
                'long_description' => '<h2>Dieu hoa tu dung LG APNQ48GT3E4 48000BTU Inverter</h2><p>Dong san pham cao cap cua LG voi cong suat 48000BTU, su dung cong nghe Inverter tiet kiem dien. Thiet ke hien dai voi man hinh LED, dieu khien tu xa qua smartphone.</p>',
                'warranty_info' => 'Bao hanh may nen 10 nam, lien may 2 nam',
                'installation_note' => 'Yeu cau nguon dien 3 pha 380V. Ong dong max 25m.',
                'specs_json' => [
                    ['label' => 'Cong suat lanh', 'value' => '48.000 BTU/h (14.0 kW)'],
                    ['label' => 'Cong nghe', 'value' => 'Inverter'],
                    ['label' => 'Gas lanh', 'value' => 'R410A'],
                    ['label' => 'Nguon dien', 'value' => '3 pha, 380V/50Hz'],
                    ['label' => 'Dien tich phong', 'value' => '50 - 70 m2'],
                    ['label' => 'Xuat xu', 'value' => 'Han Quoc'],
                ],
                'seo_title' => 'Dieu Hoa Tu Dung LG 48000BTU Inverter | Cong Nghe Thong Minh',
                'seo_description' => 'Dieu hoa tu dung LG 48000BTU Inverter, tiet kiem 50% dien. Bao hanh may nen 10 nam.',
            ],
            [
                'name' => 'Dieu hoa tu dung Panasonic CU/CS-E28NFQ 28000BTU',
                'sku' => 'PANA-E28NFQ',
                'model_code' => 'CU/CS-E28NFQ',
                'brand' => 'panasonic', 'btu' => 28000, 'inverter' => false,
                'cooling_type' => '1 chieu', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '2.8 kW',
                'airflow' => '1300 m3/h', 'noise_level' => '40/50 dB',
                'indoor_dimensions' => '1850 x 280 x 600 mm',
                'outdoor_dimensions' => '880 x 340 x 800 mm',
                'weight' => '38/55 kg', 'recommended_area' => '28-40 m2',
                'regular_price' => 26000000, 'sale_price' => 23500000,
                'is_bestseller' => true,
                'short_description' => 'Dieu hoa tu dung Panasonic 28000BTU, cong nghe NanoeX loc khong khi, van hanh ben bi.',
                'long_description' => '<h2>Dieu hoa tu dung Panasonic E28NFQ 28000BTU</h2><p>Dieu hoa tu dung Panasonic tich hop cong nghe NanoeX giup loc sach khong khi, diet khuan 99.9%. Van hanh em ai va ben bi.</p>',
                'warranty_info' => 'Bao hanh may nen 5 nam, lien may 1 nam',
                'specs_json' => [
                    ['label' => 'Cong suat lanh', 'value' => '28.000 BTU/h (8.2 kW)'],
                    ['label' => 'Cong nghe', 'value' => 'Non-Inverter'],
                    ['label' => 'Gas lanh', 'value' => 'R410A'],
                    ['label' => 'Nguon dien', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Dien tich phong', 'value' => '28 - 40 m2'],
                    ['label' => 'Xuat xu', 'value' => 'Malaysia'],
                ],
                'seo_title' => 'Dieu Hoa Tu Dung Panasonic 28000BTU | NanoeX Loc Khong Khi',
                'seo_description' => 'Dieu hoa tu dung Panasonic 28000BTU cong nghe NanoeX. Chinh hang, gia tot nhat.',
            ],
            [
                'name' => 'Dieu hoa tu dung Gree GVC36AH-M3NTB1A 36000BTU',
                'sku' => 'GREE-GVC36AH',
                'model_code' => 'GVC36AH-M3NTB1A',
                'brand' => 'gree', 'btu' => 36000, 'inverter' => false,
                'cooling_type' => '1 chieu', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '3.5 kW',
                'airflow' => '1500 m3/h', 'noise_level' => '44/54 dB',
                'indoor_dimensions' => '1800 x 350 x 530 mm',
                'outdoor_dimensions' => '950 x 410 x 1350 mm',
                'weight' => '45/78 kg', 'recommended_area' => '35-50 m2',
                'regular_price' => 22000000, 'sale_price' => 19500000,
                'is_featured' => true,
                'short_description' => 'Dieu hoa tu dung Gree 36000BTU gia re, cong suat lon, phu hop van phong va cua hang.',
                'long_description' => '<h2>Dieu hoa tu dung Gree GVC36AH 36000BTU</h2><p>Dong san pham gia tot cua Gree, cong suat 36000BTU phu hop cho van phong, cua hang, phong hop. Thiet ke gon gang, de lap dat.</p>',
                'warranty_info' => 'Bao hanh may nen 6 nam, lien may 2 nam',
                'specs_json' => [
                    ['label' => 'Cong suat lanh', 'value' => '36.000 BTU/h (10.5 kW)'],
                    ['label' => 'Cong nghe', 'value' => 'Non-Inverter'],
                    ['label' => 'Gas lanh', 'value' => 'R410A'],
                    ['label' => 'Nguon dien', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Dien tich phong', 'value' => '35 - 50 m2'],
                    ['label' => 'Xuat xu', 'value' => 'Trung Quoc'],
                ],
                'seo_title' => 'Dieu Hoa Tu Dung Gree 36000BTU | Gia Re Nhat Thi Truong',
                'seo_description' => 'Dieu hoa tu dung Gree 36000BTU gia re. Bao hanh 6 nam may nen. Giao hang mien phi.',
            ],
            [
                'name' => 'Dieu hoa tu dung Mitsubishi FDF71VD1 24000BTU 2 Chieu',
                'sku' => 'MITSU-FDF71VD1',
                'model_code' => 'FDF71VD1/FDC71VNP',
                'brand' => 'mitsubishi', 'btu' => 24000, 'inverter' => true,
                'cooling_type' => '2 chieu', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R32', 'power_consumption' => '2.5 kW',
                'airflow' => '1200 m3/h', 'noise_level' => '36/46 dB',
                'indoor_dimensions' => '1700 x 300 x 780 mm',
                'outdoor_dimensions' => '980 x 370 x 1050 mm',
                'weight' => '42/70 kg', 'recommended_area' => '25-35 m2',
                'regular_price' => 35000000, 'sale_price' => 32000000,
                'is_featured' => true, 'is_new' => true,
                'short_description' => 'Dieu hoa tu dung Mitsubishi 2 chieu Inverter, vua lam lanh vua suoi am, gas R32.',
                'long_description' => '<h2>Dieu hoa tu dung Mitsubishi FDF71VD1 2 Chieu Inverter</h2><p>San pham 2 chieu lanh/suoi cao cap, su dung gas R32 the he moi. Phu hop cho khi hau mien Bac.</p>',
                'warranty_info' => 'Bao hanh may nen 5 nam, lien may 2 nam',
                'specs_json' => [
                    ['label' => 'Cong suat lanh', 'value' => '24.000 BTU/h (7.1 kW)'],
                    ['label' => 'Cong suat suoi', 'value' => '28.000 BTU/h (8.2 kW)'],
                    ['label' => 'Cong nghe', 'value' => 'Inverter'],
                    ['label' => 'Che do', 'value' => '2 Chieu (Lanh/Suoi)'],
                    ['label' => 'Gas lanh', 'value' => 'R32'],
                    ['label' => 'Nguon dien', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Dien tich phong', 'value' => '25 - 35 m2'],
                    ['label' => 'Xuat xu', 'value' => 'Thai Lan'],
                ],
                'seo_title' => 'Dieu Hoa Tu Dung Mitsubishi 2 Chieu 24000BTU Inverter',
                'seo_description' => 'Dieu hoa tu dung Mitsubishi 2 chieu 24000BTU Inverter. Lanh/suoi, gas R32. Bao hanh 5 nam.',
            ],
            [
                'name' => 'Dieu hoa tu dung Daikin FVFC140AV1 48000BTU Inverter',
                'sku' => 'DAIKIN-FVFC140AV1',
                'model_code' => 'FVFC140AV1/RZFC140DVM',
                'brand' => 'daikin', 'btu' => 48000, 'inverter' => true,
                'cooling_type' => '1 chieu', 'voltage' => '3 pha 380V',
                'refrigerant_gas' => 'R32', 'power_consumption' => '4.5 kW',
                'airflow' => '2000 m3/h', 'noise_level' => '42/55 dB',
                'indoor_dimensions' => '1850 x 360 x 850 mm',
                'outdoor_dimensions' => '1340 x 380 x 1350 mm',
                'weight' => '58/98 kg', 'recommended_area' => '50-70 m2',
                'regular_price' => 58000000, 'sale_price' => 52500000,
                'is_featured' => true, 'is_bestseller' => true,
                'short_description' => 'Dieu hoa tu dung Daikin 48000BTU Inverter 3 pha, cong suat lon cho nha xuong, hoi truong.',
                'long_description' => '<h2>Dieu hoa tu dung Daikin FVFC140AV1 48000BTU Inverter</h2><p>Dong dieu hoa tu dung cong suat lon nhat cua Daikin. Inverter 3 pha, phu hop nha xuong, hoi truong, nha hang lon.</p>',
                'warranty_info' => 'Bao hanh may nen 5 nam, lien may 2 nam',
                'specs_json' => [
                    ['label' => 'Cong suat lanh', 'value' => '48.000 BTU/h (14.0 kW)'],
                    ['label' => 'Cong nghe', 'value' => 'Inverter'],
                    ['label' => 'Gas lanh', 'value' => 'R32'],
                    ['label' => 'Nguon dien', 'value' => '3 pha, 380V/50Hz'],
                    ['label' => 'Dien tich phong', 'value' => '50 - 70 m2'],
                    ['label' => 'Xuat xu', 'value' => 'Thai Lan'],
                ],
                'seo_title' => 'Dieu Hoa Tu Dung Daikin 48000BTU Inverter 3 Pha',
                'seo_description' => 'Dieu hoa tu dung Daikin 48000BTU Inverter 3 pha, cong suat lon. Chinh hang, bao hanh 5 nam.',
            ],
            [
                'name' => 'Dieu hoa tu dung LG APNQ24GS1A4 24000BTU Inverter',
                'sku' => 'LG-APNQ24GS1A4',
                'model_code' => 'APNQ24GS1A4',
                'brand' => 'lg', 'btu' => 24000, 'inverter' => true,
                'cooling_type' => '1 chieu', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '2.3 kW',
                'airflow' => '1100 m3/h', 'noise_level' => '39/48 dB',
                'indoor_dimensions' => '1780 x 300 x 640 mm',
                'outdoor_dimensions' => '940 x 340 x 990 mm',
                'weight' => '39/60 kg', 'recommended_area' => '25-35 m2',
                'regular_price' => 27000000, 'sale_price' => 24500000,
                'is_new' => true,
                'short_description' => 'Dieu hoa tu dung LG 24000BTU Inverter, thiet ke hien dai, loc khong khi PM1.0.',
                'long_description' => '<h2>Dieu hoa tu dung LG APNQ24GS1A4 24000BTU Inverter</h2><p>Dieu hoa tu dung LG voi bo loc PM1.0 loc bui sieu min, bao ve suc khoe gia dinh. Thiet ke sang trong, phu hop phong khach.</p>',
                'warranty_info' => 'Bao hanh may nen 10 nam, lien may 2 nam',
                'specs_json' => [
                    ['label' => 'Cong suat lanh', 'value' => '24.000 BTU/h (7.0 kW)'],
                    ['label' => 'Cong nghe', 'value' => 'Inverter'],
                    ['label' => 'Gas lanh', 'value' => 'R410A'],
                    ['label' => 'Nguon dien', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Dien tich phong', 'value' => '25 - 35 m2'],
                    ['label' => 'Xuat xu', 'value' => 'Han Quoc'],
                ],
                'seo_title' => 'Dieu Hoa Tu Dung LG 24000BTU Inverter | Loc PM1.0',
                'seo_description' => 'Dieu hoa tu dung LG 24000BTU Inverter, loc PM1.0. Bao hanh may nen 10 nam.',
            ],
        ];

        foreach ($products as $i => $p) {
            $slug = Str::slug($p['name']);
            Product::firstOrCreate(['sku' => $p['sku']], [
                'name' => $p['name'],
                'slug' => $slug,
                'sku' => $p['sku'],
                'model_code' => $p['model_code'],
                'brand_id' => $brands[$p['brand']]->id,
                'product_category_id' => $main->id,
                'btu' => $p['btu'],
                'inverter' => $p['inverter'],
                'cooling_type' => $p['cooling_type'],
                'voltage' => $p['voltage'],
                'refrigerant_gas' => $p['refrigerant_gas'],
                'power_consumption' => $p['power_consumption'],
                'airflow' => $p['airflow'],
                'noise_level' => $p['noise_level'],
                'indoor_dimensions' => $p['indoor_dimensions'] ?? null,
                'outdoor_dimensions' => $p['outdoor_dimensions'] ?? null,
                'weight' => $p['weight'],
                'recommended_area' => $p['recommended_area'],
                'regular_price' => $p['regular_price'],
                'sale_price' => $p['sale_price'],
                'discount_percent' => round((1 - $p['sale_price'] / $p['regular_price']) * 100),
                'short_description' => $p['short_description'],
                'long_description' => $p['long_description'] ?? null,
                'warranty_info' => $p['warranty_info'] ?? null,
                'installation_note' => $p['installation_note'] ?? null,
                'specs_json' => $p['specs_json'] ?? null,
                'is_featured' => $p['is_featured'] ?? false,
                'is_bestseller' => $p['is_bestseller'] ?? false,
                'is_new' => $p['is_new'] ?? false,
                'is_active' => true,
                'sort_order' => $i + 1,
                'stock_status' => 'in_stock',
                'condition' => 'new',
                'seo_title' => $p['seo_title'] ?? null,
                'seo_description' => $p['seo_description'] ?? null,
                'schema_enabled' => true,
            ]);
        }

        $this->command->info("Demo products seeded: " . count($products) . " products, 5 brands, 5 categories.");
    }
}
