<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DemoProductSeeder extends Seeder
{
    public function run(): void
    {
        // Brands
        $brands = [];
        foreach (['Daikin' => 'daikin', 'LG' => 'lg', 'Panasonic' => 'panasonic', 'Gree' => 'gree', 'Mitsubishi' => 'mitsubishi'] as $name => $slug) {
            $brands[$slug] = Brand::firstOrCreate(['slug' => $slug], ['name' => $name, 'is_active' => true]);
        }

        // Categories
        $main = ProductCategory::firstOrCreate(['slug' => 'dieu-hoa-tu-dung'], ['name' => 'Điều hòa tủ đứng']);
        $cats = [];
        foreach (['Inverter' => 'inverter', 'Non-Inverter' => 'non-inverter', '1 Chiều' => '1-chieu', '2 Chiều' => '2-chieu'] as $n => $s) {
            $cats[$s] = ProductCategory::firstOrCreate(['slug' => "dieu-hoa-tu-dung-$s"], ['name' => $n, 'parent_id' => $main->id]);
        }

        $products = [
            [
                'name' => 'Điều hòa tủ đứng Daikin FVFC71AV1 24000BTU Inverter',
                'sku' => 'DAIKIN-FVFC71AV1',
                'model_code' => 'FVFC71AV1/RZFC71DVM',
                'brand' => 'daikin', 'btu' => 24000, 'inverter' => true,
                'cooling_type' => '1 chiều', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R32', 'power_consumption' => '2.34 kW',
                'airflow' => '1100 m3/h', 'noise_level' => '38/48 dB',
                'indoor_dimensions' => '1680 x 290 x 790 mm',
                'outdoor_dimensions' => '940 x 340 x 990 mm',
                'weight' => '37/62 kg', 'recommended_area' => '25-35 m2',
                'regular_price' => 28500000, 'sale_price' => 25900000,
                'is_featured' => true, 'is_bestseller' => true, 'is_new' => true,
                'short_description' => 'Điều hòa tủ đứng Daikin Inverter 24000BTU, gas R32, cần đối chiếu thông số theo catalogue.',
                'long_description' => '<h2>Điều hòa tủ đứng Daikin FVFC71AV1 Inverter 24000BTU</h2><p>Sản phẩm điều hòa tủ đứng Daikin co cong nghe Inverter. Thông số hiệu suất và độ ồn cần đối chiếu theo catalogue hoặc dữ liệu sản phẩm đã xác minh.</p><h3>Tính năng nổi bật</h3><ul><li>Công nghệ Inverter</li><li>Gas R32 theo dữ liệu sản phẩm</li><li>Chế độ gió 3D nếu catalogue xác nhận</li></ul>',
                'warranty_info' => 'Bảo hành máy nén 5 năm, liền máy 2 năm',
                'installation_note' => 'Lắp đặt tiêu chuẩn cần báo giá theo điều kiện công trình. Ống đồng tối đa 15m theo dữ liệu sản phẩm.',
                'specs_json' => [
                    ['label' => 'Công suất lạnh', 'value' => '24.000 BTU/h (7.1 kW)'],
                    ['label' => 'Công nghệ', 'value' => 'Inverter'],
                    ['label' => 'Gas lạnh', 'value' => 'R32'],
                    ['label' => 'Nguồn điện', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Công suất tiêu thụ', 'value' => '2.34 kW'],
                    ['label' => 'Lưu lượng gió', 'value' => '1100 m3/h'],
                    ['label' => 'Độ ồn dàn lạnh', 'value' => '38 dB'],
                    ['label' => 'Độ ồn dàn nóng', 'value' => '48 dB'],
                    ['label' => 'Kích thước dàn lạnh', 'value' => '1680 x 290 x 790 mm'],
                    ['label' => 'Kích thước dàn nóng', 'value' => '940 x 340 x 990 mm'],
                    ['label' => 'Trọng lượng dàn lạnh', 'value' => '37 kg'],
                    ['label' => 'Trọng lượng dàn nóng', 'value' => '62 kg'],
                    ['label' => 'Diện tích phòng', 'value' => '25 - 35 m2'],
                    ['label' => 'Xuất xứ', 'value' => 'Thái Lan'],
                ],
                'seo_title' => 'Điều Hòa Tủ Đứng Daikin FVFC71AV1 24000BTU Inverter | Tư Vấn',
                'seo_description' => 'Điều hòa tủ đứng Daikin 24000BTU Inverter, gas R32. Đối chiếu thông số và chính sách bảo hành theo dữ liệu sản phẩm.',
            ],
            [
                'name' => 'Điều hòa tủ đứng Daikin FVGR10PV1 36000BTU Non-Inverter',
                'sku' => 'DAIKIN-FVGR10PV1',
                'model_code' => 'FVGR10PV1/RUR10NY1',
                'brand' => 'daikin', 'btu' => 36000, 'inverter' => false,
                'cooling_type' => '1 chiều', 'voltage' => '3 pha 380V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '3.65 kW',
                'airflow' => '1500 m3/h', 'noise_level' => '42/52 dB',
                'indoor_dimensions' => '1830 x 360 x 850 mm',
                'outdoor_dimensions' => '1100 x 380 x 1170 mm',
                'weight' => '52/85 kg', 'recommended_area' => '35-50 m2',
                'regular_price' => 38500000, 'sale_price' => 35900000,
                'is_featured' => true,
                'short_description' => 'Điều hòa tủ đứng Daikin 36000BTU 3 pha công suất lớn, phù hợp nhà xưởng, showroom.',
                'long_description' => '<h2>Điều hòa tủ đứng Daikin FVGR10PV1 36000BTU</h2><p>Dòng điều hòa tủ đứng công suất lớn 36000BTU, sử dụng nguồn 3 pha 380V, phù hợp cho nhà xưởng, showroom, phòng họp lớn.</p>',
                'warranty_info' => 'Bảo hành máy nén 5 năm, liền máy 2 năm',
                'installation_note' => 'Yêu cầu nguồn điện 3 pha. Ống đồng tối đa 20m theo dữ liệu sản phẩm.',
                'specs_json' => [
                    ['label' => 'Công suất lạnh', 'value' => '36.000 BTU/h (10.5 kW)'],
                    ['label' => 'Công nghệ', 'value' => 'Non-Inverter'],
                    ['label' => 'Gas lạnh', 'value' => 'R410A'],
                    ['label' => 'Nguồn điện', 'value' => '3 pha, 380V/50Hz'],
                    ['label' => 'Diện tích phòng', 'value' => '35 - 50 m2'],
                    ['label' => 'Xuất xứ', 'value' => 'Thái Lan'],
                ],
                'seo_title' => 'Điều Hòa Tủ Đứng Daikin 36000BTU 3 Pha | Công Suất Lớn',
                'seo_description' => 'Điều hòa tủ đứng Daikin 36000BTU 3 pha, phù hợp nhà xưởng, showroom. Đối chiếu chính sách bảo hành theo dữ liệu sản phẩm.',
            ],
            [
                'name' => 'Điều hòa tủ đứng LG APNQ48GT3E4 48000BTU Inverter',
                'sku' => 'LG-APNQ48GT3E4',
                'model_code' => 'APNQ48GT3E4',
                'brand' => 'lg', 'btu' => 48000, 'inverter' => true,
                'cooling_type' => '1 chiều', 'voltage' => '3 pha 380V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '4.2 kW',
                'airflow' => '2200 m3/h', 'noise_level' => '40/54 dB',
                'indoor_dimensions' => '1850 x 350 x 640 mm',
                'outdoor_dimensions' => '1340 x 380 x 1350 mm',
                'weight' => '55/95 kg', 'recommended_area' => '50-70 m2',
                'regular_price' => 52000000, 'sale_price' => 47500000,
                'is_featured' => true, 'is_new' => true,
                'short_description' => 'Điều hòa tủ đứng LG Inverter 48000BTU công suất lớn, thiết kế hiện đại.',
                'long_description' => '<h2>Điều hòa tủ đứng LG APNQ48GT3E4 48000BTU Inverter</h2><p>Dòng sản phẩm LG với công suất 48000BTU và công nghệ Inverter. Tính năng điều khiển hoặc hiệu suất cần đối chiếu theo catalogue.</p>',
                'warranty_info' => 'Bảo hành máy nén 10 năm, liền máy 2 năm',
                'installation_note' => 'Yêu cầu nguồn điện 3 pha 380V. Ống đồng tối đa 25m theo dữ liệu sản phẩm.',
                'specs_json' => [
                    ['label' => 'Công suất lạnh', 'value' => '48.000 BTU/h (14.0 kW)'],
                    ['label' => 'Công nghệ', 'value' => 'Inverter'],
                    ['label' => 'Gas lạnh', 'value' => 'R410A'],
                    ['label' => 'Nguồn điện', 'value' => '3 pha, 380V/50Hz'],
                    ['label' => 'Diện tích phòng', 'value' => '50 - 70 m2'],
                    ['label' => 'Xuất xứ', 'value' => 'Hàn Quốc'],
                ],
                'seo_title' => 'Điều Hòa Tủ Đứng LG 48000BTU Inverter | Công Nghệ Thông Minh',
                'seo_description' => 'Điều hòa tủ đứng LG 48000BTU Inverter. Đối chiếu thông số và chính sách bảo hành theo dữ liệu sản phẩm.',
            ],
            [
                'name' => 'Điều hòa tủ đứng Panasonic CU/CS-E28NFQ 28000BTU',
                'sku' => 'PANA-E28NFQ',
                'model_code' => 'CU/CS-E28NFQ',
                'brand' => 'panasonic', 'btu' => 28000, 'inverter' => false,
                'cooling_type' => '1 chiều', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '2.8 kW',
                'airflow' => '1300 m3/h', 'noise_level' => '40/50 dB',
                'indoor_dimensions' => '1850 x 280 x 600 mm',
                'outdoor_dimensions' => '880 x 340 x 800 mm',
                'weight' => '38/55 kg', 'recommended_area' => '28-40 m2',
                'regular_price' => 26000000, 'sale_price' => 23500000,
                'is_bestseller' => true,
                'short_description' => 'Điều hòa tủ đứng Panasonic 28000BTU, công nghệ NanoeX lọc không khí, vận hành cần đối chiếu theo thông số sản phẩm.',
                'long_description' => '<h2>Điều hòa tủ đứng Panasonic E28NFQ 28000BTU</h2><p>Điều hòa tủ đứng Panasonic tích hợp công nghệ NanoeX nếu được catalogue xác nhận. Hiệu quả lọc không khí, độ ồn và độ bền cần đối chiếu theo thông số sản phẩm.</p>',
                'warranty_info' => 'Bảo hành máy nén 5 năm, liền máy 1 năm',
                'specs_json' => [
                    ['label' => 'Công suất lạnh', 'value' => '28.000 BTU/h (8.2 kW)'],
                    ['label' => 'Công nghệ', 'value' => 'Non-Inverter'],
                    ['label' => 'Gas lạnh', 'value' => 'R410A'],
                    ['label' => 'Nguồn điện', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Diện tích phòng', 'value' => '28 - 40 m2'],
                    ['label' => 'Xuất xứ', 'value' => 'Malaysia'],
                ],
                'seo_title' => 'Điều Hòa Tủ Đứng Panasonic 28000BTU | NanoeX Lọc Không Khí',
                'seo_description' => 'Điều hòa tủ đứng Panasonic 28000BTU công nghệ NanoeX nếu catalogue xác nhận.',
            ],
            [
                'name' => 'Điều hòa tủ đứng Gree GVC36AH-M3NTB1A 36000BTU',
                'sku' => 'GREE-GVC36AH',
                'model_code' => 'GVC36AH-M3NTB1A',
                'brand' => 'gree', 'btu' => 36000, 'inverter' => false,
                'cooling_type' => '1 chiều', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '3.5 kW',
                'airflow' => '1500 m3/h', 'noise_level' => '44/54 dB',
                'indoor_dimensions' => '1800 x 350 x 530 mm',
                'outdoor_dimensions' => '950 x 410 x 1350 mm',
                'weight' => '45/78 kg', 'recommended_area' => '35-50 m2',
                'regular_price' => 22000000, 'sale_price' => 19500000,
                'is_featured' => true,
                'short_description' => 'Điều hòa tủ đứng Gree 36000BTU công suất lớn, phù hợp văn phòng và cửa hàng.',
                'long_description' => '<h2>Điều hòa tủ đứng Gree GVC36AH 36000BTU</h2><p>Dòng sản phẩm Gree co công suất 36000BTU. Mức giá, điều kiện lắp đặt và phù hợp công trình cần đối chiếu theo báo giá và dữ liệu sản phẩm.</p>',
                'warranty_info' => 'Bảo hành máy nén 6 năm, liền máy 2 năm',
                'specs_json' => [
                    ['label' => 'Công suất lạnh', 'value' => '36.000 BTU/h (10.5 kW)'],
                    ['label' => 'Công nghệ', 'value' => 'Non-Inverter'],
                    ['label' => 'Gas lạnh', 'value' => 'R410A'],
                    ['label' => 'Nguồn điện', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Diện tích phòng', 'value' => '35 - 50 m2'],
                    ['label' => 'Xuất xứ', 'value' => 'Trung Quốc'],
                ],
                'seo_title' => 'Điều Hòa Tủ Đứng Gree 36000BTU | Tư Vấn Theo Công Trình',
                'seo_description' => 'Điều hòa tủ đứng Gree 36000BTU. Đối chiếu giá và chính sách bảo hành theo dữ liệu sản phẩm.',
            ],
            [
                'name' => 'Điều hòa tủ đứng Mitsubishi FDF71VD1 24000BTU 2 Chiều',
                'sku' => 'MITSU-FDF71VD1',
                'model_code' => 'FDF71VD1/FDC71VNP',
                'brand' => 'mitsubishi', 'btu' => 24000, 'inverter' => true,
                'cooling_type' => '2 chiều', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R32', 'power_consumption' => '2.5 kW',
                'airflow' => '1200 m3/h', 'noise_level' => '36/46 dB',
                'indoor_dimensions' => '1700 x 300 x 780 mm',
                'outdoor_dimensions' => '980 x 370 x 1050 mm',
                'weight' => '42/70 kg', 'recommended_area' => '25-35 m2',
                'regular_price' => 35000000, 'sale_price' => 32000000,
                'is_featured' => true, 'is_new' => true,
                'short_description' => 'Điều hòa tủ đứng Mitsubishi 2 chiều Inverter, vừa làm lạnh vừa sưởi ấm, gas R32.',
                'long_description' => '<h2>Điều hòa tủ đứng Mitsubishi FDF71VD1 2 Chiều Inverter</h2><p>San pham 2 chiều lạnh/sưởi cao cap, su dung gas R32 the he moi. Phu hop cho khi hau mien Bac.</p>',
                'warranty_info' => 'Bảo hành máy nén 5 năm, liền máy 2 năm',
                'specs_json' => [
                    ['label' => 'Công suất lạnh', 'value' => '24.000 BTU/h (7.1 kW)'],
                    ['label' => 'Công suất sưởi', 'value' => '28.000 BTU/h (8.2 kW)'],
                    ['label' => 'Công nghệ', 'value' => 'Inverter'],
                    ['label' => 'Chế độ', 'value' => '2 Chiều (Lanh/Suoi)'],
                    ['label' => 'Gas lạnh', 'value' => 'R32'],
                    ['label' => 'Nguồn điện', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Diện tích phòng', 'value' => '25 - 35 m2'],
                    ['label' => 'Xuất xứ', 'value' => 'Thái Lan'],
                ],
                'seo_title' => 'Điều Hòa Tủ Đứng Mitsubishi 2 Chiều 24000BTU Inverter',
                'seo_description' => 'Điều hòa tủ đứng Mitsubishi 2 chiều 24000BTU Inverter, lạnh/sưởi, gas R32 theo dữ liệu sản phẩm.',
            ],
            [
                'name' => 'Điều hòa tủ đứng Daikin FVFC140AV1 48000BTU Inverter',
                'sku' => 'DAIKIN-FVFC140AV1',
                'model_code' => 'FVFC140AV1/RZFC140DVM',
                'brand' => 'daikin', 'btu' => 48000, 'inverter' => true,
                'cooling_type' => '1 chiều', 'voltage' => '3 pha 380V',
                'refrigerant_gas' => 'R32', 'power_consumption' => '4.5 kW',
                'airflow' => '2000 m3/h', 'noise_level' => '42/55 dB',
                'indoor_dimensions' => '1850 x 360 x 850 mm',
                'outdoor_dimensions' => '1340 x 380 x 1350 mm',
                'weight' => '58/98 kg', 'recommended_area' => '50-70 m2',
                'regular_price' => 58000000, 'sale_price' => 52500000,
                'is_featured' => true, 'is_bestseller' => true,
                'short_description' => 'Điều hòa tủ đứng Daikin 48000BTU Inverter 3 pha, công suất lớn cho nhà xưởng, hội trường.',
                'long_description' => '<h2>Điều hòa tủ đứng Daikin FVFC140AV1 48000BTU Inverter</h2><p>Dòng điều hòa tủ đứng công suất lớn nhat cua Daikin. Inverter 3 pha, phù hợp nhà xưởng, hội trường, nhà hàng lớn.</p>',
                'warranty_info' => 'Bảo hành máy nén 5 năm, liền máy 2 năm',
                'specs_json' => [
                    ['label' => 'Công suất lạnh', 'value' => '48.000 BTU/h (14.0 kW)'],
                    ['label' => 'Công nghệ', 'value' => 'Inverter'],
                    ['label' => 'Gas lạnh', 'value' => 'R32'],
                    ['label' => 'Nguồn điện', 'value' => '3 pha, 380V/50Hz'],
                    ['label' => 'Diện tích phòng', 'value' => '50 - 70 m2'],
                    ['label' => 'Xuất xứ', 'value' => 'Thái Lan'],
                ],
                'seo_title' => 'Điều Hòa Tủ Đứng Daikin 48000BTU Inverter 3 Pha',
                'seo_description' => 'Điều hòa tủ đứng Daikin 48000BTU Inverter 3 pha, công suất lon. Đối chiếu chính sách bảo hành theo dữ liệu sản phẩm.',
            ],
            [
                'name' => 'Điều hòa tủ đứng LG APNQ24GS1A4 24000BTU Inverter',
                'sku' => 'LG-APNQ24GS1A4',
                'model_code' => 'APNQ24GS1A4',
                'brand' => 'lg', 'btu' => 24000, 'inverter' => true,
                'cooling_type' => '1 chiều', 'voltage' => '1 pha 220V',
                'refrigerant_gas' => 'R410A', 'power_consumption' => '2.3 kW',
                'airflow' => '1100 m3/h', 'noise_level' => '39/48 dB',
                'indoor_dimensions' => '1780 x 300 x 640 mm',
                'outdoor_dimensions' => '940 x 340 x 990 mm',
                'weight' => '39/60 kg', 'recommended_area' => '25-35 m2',
                'regular_price' => 27000000, 'sale_price' => 24500000,
                'is_new' => true,
                'short_description' => 'Điều hòa tủ đứng LG 24000BTU Inverter, thiet ke hien dai, loc khong khi PM1.0.',
                'long_description' => '<h2>Điều hòa tủ đứng LG APNQ24GS1A4 24000BTU Inverter</h2><p>Điều hòa tủ đứng LG với bộ lọc PM1.0 nếu catalogue xác nhận. Thiết kế phù hợp cần đối chiếu theo không gian lắp đặt thực tế.</p>',
                'warranty_info' => 'Bảo hành máy nén 10 năm, liền máy 2 năm',
                'specs_json' => [
                    ['label' => 'Công suất lạnh', 'value' => '24.000 BTU/h (7.0 kW)'],
                    ['label' => 'Công nghệ', 'value' => 'Inverter'],
                    ['label' => 'Gas lạnh', 'value' => 'R410A'],
                    ['label' => 'Nguồn điện', 'value' => '1 pha, 220V/50Hz'],
                    ['label' => 'Diện tích phòng', 'value' => '25 - 35 m2'],
                    ['label' => 'Xuất xứ', 'value' => 'Hàn Quốc'],
                ],
                'seo_title' => 'Điều Hòa Tủ Đứng LG 24000BTU Inverter | Lọc PM1.0',
                'seo_description' => 'Điều hòa tủ đứng LG 24000BTU Inverter, lọc PM1.0 nếu catalogue xác nhận.',
            ],
        ];

        foreach ($products as $i => $p) {
            $slug = Str::slug($p['name']);
            Product::firstOrCreate(['sku' => $p['sku']], [
                'name' => $p['name'],
                'slug' => $slug,
                'sku' => $p['sku'],
                'model_code' => $p['model_code'],
                'brand_id' => $brands[$p['brand']]->id,
                'product_category_id' => $main->id,
                'btu' => $p['btu'],
                'inverter' => $p['inverter'],
                'cooling_type' => $p['cooling_type'],
                'voltage' => $p['voltage'],
                'refrigerant_gas' => $p['refrigerant_gas'],
                'power_consumption' => $p['power_consumption'],
                'airflow' => $p['airflow'],
                'noise_level' => $p['noise_level'],
                'indoor_dimensions' => $p['indoor_dimensions'] ?? null,
                'outdoor_dimensions' => $p['outdoor_dimensions'] ?? null,
                'weight' => $p['weight'],
                'recommended_area' => $p['recommended_area'],
                'regular_price' => $p['regular_price'],
                'sale_price' => $p['sale_price'],
                'discount_percent' => round((1 - $p['sale_price'] / $p['regular_price']) * 100),
                'short_description' => $p['short_description'],
                'long_description' => $p['long_description'] ?? null,
                'warranty_info' => $p['warranty_info'] ?? null,
                'installation_note' => $p['installation_note'] ?? null,
                'specs_json' => $p['specs_json'] ?? null,
                'is_featured' => $p['is_featured'] ?? false,
                'is_bestseller' => $p['is_bestseller'] ?? false,
                'is_new' => $p['is_new'] ?? false,
                'is_active' => true,
                'sort_order' => $i + 1,
                'stock_status' => 'in_stock',
                'condition' => 'new',
                'seo_title' => $p['seo_title'] ?? null,
                'seo_description' => $p['seo_description'] ?? null,
                'schema_enabled' => true,
            ]);
        }

        $this->command->info("Demo products seeded: " . count($products) . " products, 5 brands, 5 categories.");
    }
}
