<?php

return [
    'schema_version' => 'content-layer-runtime-contract-v1',

    'content_layer_fields' => [
        'excerpt',
        'content_html',
        'seo_title',
        'meta_description',
        'og_title',
        'og_description',
        'merchant_title',
        'merchant_description',
        'tags',
        'faq',
        'internal_links',
        'media_metadata',
        'warnings',
        'blocked_claims',
        'used_facts',
        'used_verified_facts',
        'product_id',
    ],

    'blocked_product_data_fields' => [
        'basic_info',
        'technical_specs',
        'technical_specs_json',
        'name',
        'slug',
        'sku',
        'model',
        'model_code',
        'brand',
        'brand_id',
        'category',
        'category_id',
        'product_category_id',
        'series',
        'capacity_btu',
        'btu',
        'marketing_capacity_btu',
        'technical_capacity_btu',
        'technical_capacity_status',
        'catalog_source_id',
        'catalog_model_id',
        'catalog_provenance',
        'source_catalogue',
        'source_page',
        'capacity_kw',
        'hp',
        'cooling_type',
        'inverter',
        'phase',
        'voltage',
        'refrigerant',
        'refrigerant_gas',
        'power_consumption',
        'power_input_kw',
        'airflow',
        'noise_level',
        'recommended_area',
        'indoor_dimensions',
        'outdoor_dimensions',
        'dimensions',
        'weight',
        'pipe_liquid',
        'pipe_gas',
        'pipe_max_length',
        'pipe_max_height',
        'regular_price',
        'sale_price',
        'discount_percent',
        'stock_status',
        'specs_json',
    ],
];
